version: '3.7'

services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - order-net
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - $PWD/../storages/mongo:/data/db
    networks:
      - order-net
  mysql_server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "orderdb"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/../storages/mysql:/var/lib/mysql
    networks:
      - order-net
networks:
  order-net: