server:
  port: 8080

eureka:
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true