server:
  port: 9002
spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:mem:product_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect